1.Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


2.Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:

arr1,arr2 = (list(map(int,input().split())) for i in range(2))
arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(np.concatenate((arr1,arr2)))
print(np.sort(np.concatenate((arr1,arr2))))

2 6 7 9 8
1 5 2 3 4 
[2 6 7 9 8 1 5 2 3 4]
[1 2 2 3 4 5 6 7 8 9]


3.Write a code snippet to find the dimensions of a ndarray and its size.

In [5]:

arr = np.array([ [1,2] , [4,5]  ])
print(arr.shape,arr.size)

(2, 2) 4


4.How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

In [8]:
import numpy as np
x= np.array([1, 2, 3, 4, 5, 6,7,8])
print("1D array  :",x)
print("1D array shape :",x.shape)

y = x[np.newaxis, :]
print("2D array  :",y)
print("After converting 1D array into  2D array the shape :",y.shape)

1D array  : [1 2 3 4 5 6 7 8]
1D array shape : (8,)
2D array  : [[1 2 3 4 5 6 7 8]]
After converting 1D array into  2D array the shape : (1, 8)


5.Consider two square numpy arrays. Stack them vertically and horizontally.Hint: Use vstack(), hstack()

In [10]:
arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])
print(" vertically",np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence

print("horizontally",np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence

 vertically [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]
horizontally [[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


 6.How to get unique items and counts of unique items?

In [13]:
import numpy as np
a=np.unique([0,1,2,0,2,3,4,3,6,7])
print("unique items :",a)
print("counts of unique items :",len(a))


unique items : [0 1 2 3 4 6 7]
counts of unique items : 7
